### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by pjuda** [UniNE-CHYN/mps_toolbox#3]
I created a dev branch, where I corrected the __init__ file and cleaned up the cache files. However, the build still fails (you can see it by clicking the button in README). It is due to the fact that pytest called from the repository root directory fails to see the files. Could you look at it @GCoiffier ?

**Comment by GCoiffier** [comment]
Indeed, pytest is called from the root directory with travis, whereas I was running my tests from the tests/ folder.
The test _image.py has been corrected to be run from rootdir, and the project now builds just fine.
