### ISSUE TITLE
Enforce PEP8 compliance

### ISSUE THREAD

**Issue by pjuda** [UniNE-CHYN/mps_toolbox#6]
I changed travis configuration on branch `dev` so that it uses `pycodestyle` for checking PEP8 compliance.

The command to check it from mps_toolbox root: `pycodestyle mpstool tests` will check PEP8 in the directories `mpstool` and `tests`. We can use `autopep8` tool to do some automatic PEP8 conversion.

To be discussed: enforcement of the line length <80.

After making `dev` PEP8-compliant, let's merge it into `master`.

**Comment by pjuda** [comment]
I changed my modules so that they conform to PEP8 entirely (including line length - I think it is a good practice to try to keep lines shorter). 

Should I continue with the rest of the codebase or do you prefer to do it yourself for the modules and tests you contributed, @GCoiffier ?

I noticed you'd included try/except in the `__init__.py`. What is the use of it? The bare except causes the following problem: `E722 do not use bare except`

**Comment by GCoiffier** [comment]
I changed `img.py` to respect the PEP8, including line length.

The reason I used try/excepts in import is for compatibility : I wanted the module to be usable without installing all the dependencies. For instance, you can make use of the gslib file format I/O without having to bother with the vox parser

These try/except scopes have been fixed to handle only ImportError, which gets rid of the "bare except" warning.
